//modals
export const TOGGLE_REGISTER_MODAL = 'TOGGLE_REGISTER_MODAL';
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const TOGGLE_LOGOUT_MODAL = 'TOGGLE_LOGOUT_MODAL';
export const TOGGLE_LOGOUT_LOADING = 'TOGGLE_LOGOUT_LOADING';
export const TOGGLE_ACCOUNT_MODAL = 'TOGGLE_ACCOUNT_MODAL';

export const OPEN_RESULT_MODAL = 'OPEN_RESULT_MODAL';
export const CLOSE_RESULT_MODAL = 'CLOSE_RESULT_MODAL';
export const LOAD_RESULT_MODAL_DATA = 'LOAD_RESULT_MODAL_DATA';
export const RESET_RESULT_MODAL_DATA = 'RESET_RESULT_MODAL_DATA';

//drawers
export const TOGGLE_NAV_DRAWER = 'TOGGLE_NAV_DRAWER';
export const CLOSE_NAV_DRAWER = 'CLOSE_NAV_DRAWER';

//user authentication
export const AUTH_USER = 'AUTH_USER';
export const DEAUTH_USER = 'DEAUTH_USER';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const TOGGLE_REGISTER_BUTTON_LOADING = 'TOGGLE_REGISTER_BUTTON_LOADING';
export const TOGGLE_LOGIN_BUTTON_LOADING = 'TOGGLE_LOGIN_BUTTON_LOADING';

//load user
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADED_SET_LOCATION = 'USER_LOADED_SET_LOCATION';
export const AUTH_ERROR = 'AUTH_ERROR';

//create post - publish
export const PUBLISH_LOADING = 'PUBLISH_LOADING';
export const PUBISH_LOADING_DONE = 'PUBISH_LOADING_DONE';
export const REDIRECT_TO_HOME = 'REDIRECT_TO_HOME';

//post steps
export const CHANGE_POST_STEP = 'CHANGE_POST_STEP';

//img upload
export const OBJECTURL_IMG_URL = 'OBJECTURL_IMG_URL';
export const DEFAULT_IMG_URL = 'DEFAULT_IMG_URL';
export const THUMBNAIL_IMG_URL = 'THUMBNAIL_IMG_URL';
export const INCREASE_IMG_KEY = 'INCREASE_IMG_KEY';
export const DECREASE_IMG_KEY = 'DECREASE_IMG_KEY';
export const IMAGE_UPLOADING_TRUE = 'IMAGE_UPLOADING_TRUE';
export const IMAGE_UPLOADING_FALSE = 'IMAGE_UPLOADING_FALSE';
export const DELETE_IMG_PREVIEW = 'DELETE_IMG_PREVIEW';
export const IMG_UPLOAD_DONE = 'IMG_UPLOAD_DONE';
export const EMPTY_IMGLIST = 'EMPTY_IMGLIST';

//location
export const UPDATE_GEOLOCATION = 'UPDATE_GEOLOCATION';
export const LOADING_USER_LOCATION = 'LOADING_USER_LOCATION';
export const LOADING_USER_LOCATION_DONE = 'LOADING_USER_LOCATION_DONE';
export const SAVING_USER_LOCATION = 'SAVING_USER_LOCATION';
export const SAVING_USER_LOCATION_DONE = 'SAVING_USER_LOCATION_DONE';
export const DISPLAY_LOCATION_FORM = 'DISPLAY_LOCATION_FORM';
export const HIDE_LOCATION_FORM = 'HIDE_LOCATION_FORM';

//Post modal
export const OPEN_POST_MODAL = 'OPEN_POST_MODAL';
export const CLOSE_POST_MODAL = 'CLOSE_POST_MODAL';

//Posts
export const LOAD_POSTS = 'LOAD_POSTS';
export const UPDATE_SELECTED_POST = 'UPDATE_SELECTED_POST';
