export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const TOGGLE_REGISTER_MODAL = 'TOGGLE_REGISTER_MODAL';
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const ADD_AUTH_ERROR = 'ADD_AUTH_ERROR';
export const TOGGLE_AUTH_LOADING = 'TOGGLE_AUTH_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
